config/routes.rb
# encoding: UTF-8

Rails.application.routes.draw do

  rutarel = ENV.fetch('RUTA_RELATIVA', 'cor1440/')
  scope rutarel do 
    devise_scope :usuario do
      #get 'sign_out' => 'devise/sessions#destroy'
      get 'sign_out' => 'sessions#destroy', as: :sign_out
      get 'usuarios/sign_in' => 'sessions#new', as: :sign_in
      get 'sign_up' => 'registrations#new', as: :sign_up

      #root 'sessions#new' 

      # El siguiente para superar mala generación del action en el formulario
      # cuando se autentica mal (genera 
      # /puntomontaje/puntomontaje/usuarios/sign_in )
      if (Rails.configuration.relative_url_root != '/') 
        ruta = File.join(Rails.configuration.relative_url_root, 
                         'usuarios/sign_in')
        post ruta, to: 'devise/sessions#create'
      end
    end
    devise_for :usuarios, module: :devise, 
      controllers: { registrations: "registrations" }
    #devise_for :usuarios, :skip => [:registrations], module: :devise
    as :usuario do
      get 'usuarios/edit' => 'devise/registrations#edit', 
        :as => 'editar_registro_usuario'    
      put 'usuarios/:id' => 'devise/registrations#update', 
        :as => 'registro_usuario'            
    end
    resources :usuarios, path_names: { new: 'nuevo', edit: 'edita' } 

    post 'usuarios/crea' => 'usuarios#create', :as => 'crea_usuario'           
    patch 'usuarios/:id/actualiza' => 'usuarios#update', 
      :as => 'actualiza_usuario'           
    get 'usuarios/reconfirma' => 'usuarios#reconfirma'
    post 'bitacora/admin' => 'sal7711_gen/bitacora#admin', 
      as: 'bitacora_publica'
    get 'bitacora/admin' => 'sal7711_gen/bitacora#admin', 
      as: 'bitacora_admin'
    get 'bitacora/tiempo' => 'sal7711_gen/bitacora#tiempo', 
      as: 'bitacora_tiempo'

    get 'lotes/nuevo' => 'lotes#new', as: 'new_lote'
    post  'lotes/nuevo' => 'lotes#create', as: 'create_lote'

    get 'lotes/ocrfaltante' => 'lotes#ocrfaltante', as: 'ocrfaltante'
    #  resource 'contacto', only: [:new, :create]

    resources 'lotes', only: [:new, :create, :index], 
      path_names: { new: 'nuevo', edit: 'edita' }

    root 'sal7711_gen/hogar#index'

#    namespace :admin do
#      ab = ::Ability.new
#      ab.tablasbasicas.each do |t|
#        #puts "OJO config/routes.rb, t=" + t.to_s
#        if (t[0] == "") 
#          c = t[1].pluralize
#          resources c.to_sym, 
#            path_names: { new: 'nueva', edit: 'edita' }
#        end
#      end
#    end

  end

  mount Sal7711Gen::Engine, at: rutarel, as: 'sal7711_gen'
  mount Sip::Engine, at: rutarel, as: 'sip'

end

app/views/layouts/application.html.erb
<% content_for :titulo do %>
    <%= Sip.titulo %>
<% end %>

<% content_for :marca do %>
  <img class='logo-cinep' src='/assets/logo.png'> 
  <!--%= Sip.titulo %-->
<% end %>

<% content_for :menu do %>
  <%= grupo_menus do %>
    <% if current_usuario %>
      <%= opcion_menu 'Buscar', sal7711_gen.buscar_path %>
      <%= opcion_menu 'Manual de Uso', '/Manual_de_Uso_Archivo_Digital_de_Prensa_CINEP.pdf', target: '_blank' %>
      <% if can? :edit, Sal7711Gen::Articulo %>
        <%= despliega_abajo 'Lote' do %>
          <%= opcion_menu 'Buscar', main_app.lotes_path, 
            desplegable: true %>
          <%= opcion_menu 'Añadir un lote', main_app.new_lote_path,
            desplegable: true %>
          <!--%= opcion_menu 'Añadir un artículo', sal7711_gen.new_articulo_path %-->
        <% end %>
      <% end %>
    <% else %>
      <!-- %= opcion_menu 'Presentacion', 
        main_app.presentacion_path %-->
      <%= opcion_menu 'Acerca de', sip.acercade_path %>
    <% end %>
  <% end %>
  <%= grupo_menus :pull => :right do %>
    <% urlop = Rails.configuration.action_mailer.default_url_options %>
        
    <% if current_usuario && !current_usuario.autenticado_por_ip %>
        <%= despliega_abajo 'Administrar' do %>
          <% if can? :cambiarclave, ::Usuario %>
            <%= opcion_menu 'Clave y tema', main_app.editar_registro_usuario_path,
              desplegable: true %>
          <% end %>
          <% if current_usuario.rol == Ability::ROLADMIN %>
             <%= opcion_menu 'Usuarios', main_app.usuarios_path,
               desplegable: true %>
             <%= opcion_menu 'Tablas Básicas', sip.tablasbasicas_path,
               desplegable: true %>
             <%= opcion_menu 'Bitácora', '/bitacora/admin',
               desplegable: true %>
             <%= opcion_menu 'Consultas en tiempo', '/bitacora/tiempo',
               desplegable: true %>
             <%= opcion_menu 'Ejecutar OCR en artículos faltantes', 
               '/lotes/ocrfaltante', desplegable: true %>
          <% end %>
          <%= opcion_menu 'Ver Control de Acceso', 
            sip.ayuda_controldeacceso_path, desplegable: true %>
        <% end %>
        <% if !current_usuario.autenticado_por_ip %>
          <%= opcion_menu "Salir #{current_usuario.nusuario}", 
            main_app.sign_out_path %>
        <% end %>
     <% elsif !current_usuario %>
      <%= opcion_menu 'Iniciar Sesión', main_app.new_usuario_session_path %>
      <%= opcion_menu 'Inscribirse', main_app.sign_up_path %>
    <% end %> <!-- else current_usuario -->
  <% end %> <!-- grupo_menus -->
<% end %> <!-- content_for :menu -->

<% content_for :piedepagina do %>
  <div class='pie'>
    <p> Contenidos con derechos reservados. Pueden ser utilizado total o 
    parcialmente, siempre y cuando se cite como fuente al 
      <a href='http://www.cinep.org.co'>CINEP/Programa por la Paz</a>.</p>
    <p>Teléfono: (57)(1) 245.6181  /  
    Fax: (57)(1) 287.9089  /  
    Email: <a href='mailto:cinep@cinep.org.co'>cinep@cinep.org.co</a>  /  
    Dirección: Cra 5 No. 33B- 02 Bogotá, Colombia.</p>
    <p>Sistema de información desarrollado por 
      <a href='http://www.pasosdeJesus.org'>Pasos de Jesús</a>
    </p>
  </div>
<% end %>

<%= render template: 'layouts/sal7711_gen/application' %>